name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed 👀

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: '🚨 Breaking'
    label: 'breaking'
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    lable: 'bug'
  - title: '🧰 Maintenance'
    label: 'maintenance'
  - title: '📄 Documentation'
    label: 'docs'
  - title: 🔐 Security
    labels: 'security'
    collapse-after: 5


version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'docs'
      - 'dependencies'
      - 'security'

exclude-labels:
  - 'skip-changelog'
