name: Update cms/master

on:
  push:
    branches:
      - main

jobs:
  update-cms-master:
    name: Merge master into release after a PR is merged
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
      pages: write
      id-token: write
      packages: write
    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: COnfigure git
      run: |
        author_name=$(git log -1 --format='%an')
        author_email=$(git log -1 --format='%ae')
        git config --global user.email "$author_email"
        git config --global user.name "$author_name"
        
    - name: Perform rebase
      run: |
        git fetch origin main
        git checkout release/2.14.0
        git merge origin/main
        git push -u origin release/2.14.0 --force

    # - name: Push changes
    #   uses: CasperWA/push-protected@v2.15.0
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     branch: release/2.14.0
    #     unprotect_reviews: True
    #     force: True
  #     - name: checkout
  #       uses: actions/checkout@v2
  #     - name: merge
  #       uses: mtanzi/action-automerge@v1
  #       id: merge
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         source: 'main'
  #         target: 'release/2.14.0'
