name: CI
# This workflow is triggered when a PR is opened on master or develop branch
on:
  pull_request:
    branches:
      - main
      - release/*
      - epic/*


jobs:
  remove_old_branches:
    name: Remove old release branches
    #if: "contains(github.event.head_commit.message, '[skip test-ci]')"
    if: ${{ !contains(github.event.head_commit.message, '#skipci') }}
    runs-on: ubuntu-latest
    steps:
    - run:  |
        echo ${{ github.event.head_commit.message }}

