name: Remove Branch's
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  INFRASTRUCTURE_TOKEN: ${{ secrets.INFRASTRUCTURE_TOKEN }}
  TEST_ENV: 'test'

jobs:
  remove_old_branches:
    name: Remove old release branches
    runs-on: macos-14-arm64
    steps:
    - run: uname -a
