name: Remove Branch's
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  INFRASTRUCTURE_TOKEN: ${{ secrets.INFRASTRUCTURE_TOKEN }}
  TEST_ENV: 'test'

jobs:
  remove_old_branches:
    name: Remove old release branches
    runs-on: macos-14
    steps:
    - run:  |
        # sudo launchctl unload /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist
        sudo launchctl load /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist
        sudo lsof -i -P -n
        ping google.com

