name: Remove Branch's
on:
  workflow_dispatch:
  branch:
    - main

env:
  INFRASTRUCTURE_TOKEN: ${{ secrets.INFRASTRUCTURE_TOKEN }}
  TEST_ENV: 'test'

jobs:
  remove_old_branches:
    name: Remove old release branches
    runs-on: macOS-latest
    steps:
    - run: id -u && id -g
