name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  setup_job:
    runs-on: ubuntu-24.04
    steps:
      - name: test
        run: |
          cat /etc/os-release
          which gcloud
