name: 01
on:
  push:
    branches:
      - main

jobs:
  setup_job:
    runs-on: macOS-latest
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
      - run: echo  "${{ steps.create_token.outputs.token }}"

      
